# Generated by Django 5.2 on 2025-04-11 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_image_news_posted_by_alter_news_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
